"""Transactional storage and bounded retention for HTTP request metadata.

Callers must pass a *router-declared* path template, never the request URL. A
request that did not match a router uses the fixed marker below. This repository
rejects obvious raw URLs, but the HTTP integration must enforce that provenance.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Literal

from sqlalchemy import Connection, delete, insert, select

from patchouli_lib.request_log.models import RequestLogRecord

UNMATCHED_ROUTE = "<unmatched>"
_REQUEST_ID = re.compile(r"req_[0-9a-f]{32}\Z", re.ASCII)
_OPAQUE_ID = re.compile(r"[0-9a-f]{32}\Z", re.ASCII)
_ROUTE = re.compile(
    r"/(?:[A-Za-z0-9._~-]+|\{[A-Za-z_][A-Za-z0-9_]*(?::path)?\})"
    r"(?:/(?:[A-Za-z0-9._~-]+|\{[A-Za-z_][A-Za-z0-9_]*(?::path)?\}))*\Z"
    r"|/\Z",
    re.ASCII,
)
_METHODS = frozenset({"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "OTHER"})
_MAX_SQLITE_INT = (1 << 63) - 1


@dataclass(frozen=True, slots=True)
class RequestLogWrite:
    request_id: str
    method: str
    route_template: str
    status_code: int | None
    completion: Literal["completed", "interrupted"]
    occurred_at: int
    duration_us: int
    caller_id: str | None = None
    home_library_id: str | None = None
    credential_id: str | None = None

    def __post_init__(self) -> None:
        if type(self.request_id) is not str or _REQUEST_ID.fullmatch(self.request_id) is None:
            raise ValueError("Request ID must be generated by the server.")
        if type(self.method) is not str or self.method not in _METHODS:
            raise ValueError("Unsupported HTTP method.")
        if (
            type(self.route_template) is not str
            or not 1 <= len(self.route_template) <= 240
            or (
                self.route_template != UNMATCHED_ROUTE
                and _ROUTE.fullmatch(self.route_template) is None
            )
        ):
            raise ValueError("A router template or the unmatched marker is required.")
        if type(self.completion) is not str or self.completion not in {
            "completed",
            "interrupted",
        }:
            raise ValueError("Invalid completion state.")
        if self.status_code is None:
            if self.completion != "interrupted":
                raise ValueError("Completed requests require an HTTP status.")
        elif type(self.status_code) is not int or not 100 <= self.status_code <= 599:
            raise ValueError("Invalid HTTP status.")
        if type(self.occurred_at) is not int or not 0 <= self.occurred_at <= _MAX_SQLITE_INT:
            raise ValueError("Invalid UTC event timestamp.")
        if type(self.duration_us) is not int or not 0 <= self.duration_us <= _MAX_SQLITE_INT:
            raise ValueError("Invalid monotonic duration.")
        for identity in (self.caller_id, self.home_library_id, self.credential_id):
            if identity is not None and (
                type(identity) is not str or _OPAQUE_ID.fullmatch(identity) is None
            ):
                raise ValueError("Invalid identity metadata.")
        if self.credential_id is not None and self.caller_id is None:
            raise ValueError("A credential ID requires a caller ID.")


class RequestLogRepository:
    """Write/delete request metadata in the caller's existing transaction."""

    def __init__(self, connection: Connection) -> None:
        self._connection = connection

    def add(self, entry: RequestLogWrite) -> int:
        if not self._connection.in_transaction():
            raise RuntimeError("Request logging requires an active transaction.")
        row = self._connection.execute(
            insert(RequestLogRecord).returning(RequestLogRecord.id),
            {
                "request_id": entry.request_id,
                "method": entry.method,
                "route_template": entry.route_template,
                "status_code": entry.status_code,
                "completion": entry.completion,
                "occurred_at": entry.occurred_at,
                "duration_us": entry.duration_us,
                "caller_id": entry.caller_id,
                "home_library_id": entry.home_library_id,
                "credential_id": entry.credential_id,
            },
        )
        return row.scalar_one()

    def get(self, request_id: str) -> RequestLogWrite | None:
        if type(request_id) is not str or _REQUEST_ID.fullmatch(request_id) is None:
            raise ValueError("Invalid request ID.")
        row = (
            self._connection.execute(
                select(
                    RequestLogRecord.request_id,
                    RequestLogRecord.method,
                    RequestLogRecord.route_template,
                    RequestLogRecord.status_code,
                    RequestLogRecord.completion,
                    RequestLogRecord.occurred_at,
                    RequestLogRecord.duration_us,
                    RequestLogRecord.caller_id,
                    RequestLogRecord.home_library_id,
                    RequestLogRecord.credential_id,
                ).where(RequestLogRecord.request_id == request_id)
            )
            .mappings()
            .one_or_none()
        )
        return None if row is None else RequestLogWrite(**dict(row))

    def delete_before(self, cutoff_utc_us: int, *, batch_size: int = 1_000) -> int:
        """Delete at most one batch strictly older than the supplied UTC cutoff."""

        if not self._connection.in_transaction():
            raise RuntimeError("Retention cleanup requires an active transaction.")
        if type(cutoff_utc_us) is not int or not 0 <= cutoff_utc_us <= _MAX_SQLITE_INT:
            raise ValueError("Invalid UTC retention cutoff.")
        if type(batch_size) is not int or not 1 <= batch_size <= 10_000:
            raise ValueError("Invalid retention batch size.")
        subquery = (
            select(RequestLogRecord.id)
            .where(RequestLogRecord.occurred_at < cutoff_utc_us)
            .order_by(RequestLogRecord.occurred_at, RequestLogRecord.id)
            .limit(batch_size)
        )
        result = self._connection.execute(
            delete(RequestLogRecord).where(RequestLogRecord.id.in_(subquery))
        )
        return result.rowcount


__all__ = ["UNMATCHED_ROUTE", "RequestLogRepository", "RequestLogWrite"]
